name: Update YouTube stats

on:
  workflow_dispatch:

jobs:
  metadata-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout channel config file
      uses: actions/checkout@v3.5.3
      with: 
        sparse-checkout: |
          automation/channels.txt
        sparse-checkout-cone-mode: false
    - name: Updating data
      run: |
        headerPrefix="header:"
        while read line; do
          if [[ $line == $headerPrefix* ]]; then
            echo "Header: $line"
          else
            echo "Text read from file: $line"
            OUTPUT=$(curl 'https://youtube.googleapis.com/youtube/v3/channels?part=statistics&forUsername=Jerma985&key=${{ secrets.API_KEY }}' \
              --header 'Accept: application/json' \
              --compressed)
            echo "Output: $OUTPUT"
          fi
        done < ${{ github.workspace }}/automation/channels.txt
