name: Update YouTube stats

on:
  workflow_dispatch:

jobs:
  metadata-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout channel config file
      uses: actions/checkout@v3.5.3
      with: 
        sparse-checkout: |
          automation/channels.txt
        sparse-checkout-cone-mode: false
    - name: Updating data
      run: |
        headerPrefix="header:"
        echo "About to start"
        while read line; do
          if [[ $line == $headerPrefix* ]]; then
            echo "$line" | sed 's/header:/####'
          else
            echo "About to try $line"
            OUTPUT_JSON=curl 'https://youtube.googleapis.com/youtube/v3/channels?part=statistics&forUsername=Jerma985&key=${{ secrets.API_KEY }}' \
              --header 'Accept: application/json' \
              --compressed >> $GITHUB_ENV
            echo OUTPUT_JSON
            echo "$line has ${{ fromJson(env.OUTPUT_JSON).items[0].statistics.subscriberCount }} subscribers, ${{ fromJson(env.OUTPUT_JSON).items[0].statistics.videoCount }} videos, and ${{ fromJson(env.OUTPUT_JSON).items[0].statistics.viewCount }} video views."
          fi
        done < ${{ github.workspace }}/automation/channels.txt
