name: Update YouTube stats

on:
  workflow_dispatch:

jobs:
  metadata-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout channel config file
      uses: actions/checkout@v3.5.3
      with: 
        sparse-checkout: |
          automation/channels.txt
        sparse-checkout-cone-mode: false
    - name: Parsing data
      run: |
        headerPrefix="header:"
        while read line; do
          if [[ $line == $headerPrefix* ]]; then
            echo "Header line: $line"
          else
            echo "Text read from file: $line"
          fi
        done < ${{ github.workspace }}/automation/channels.txt
        curl 'https://youtube.googleapis.com/youtube/v3/channels?part=statistics&forUsername=Jerma985&key=${{ secrets.API_KEY }}' \
          --header 'Accept: application/json' \
          --compressed \
          -o output.json
    - name: Save JSON into env var
      run: echo "OUTPUT_JSON=$(jq -c . < output.json)" >> $GITHUB_ENV
    - name: Output JSON for debug
      run: echo '${{ env.OUTPUT_JSON }}'
    - name: Pull data out of JSON
      run: |
        echo "This channel has "
        echo "${{ fromJson(env.OUTPUT_JSON).items[0].statistics.subscriberCount }} subscribers, "
        echo "${{ fromJson(env.OUTPUT_JSON).items[0].statistics.videoCount }} videos, and "
        echo "${{ fromJson(env.OUTPUT_JSON).items[0].statistics.viewCount }} video views."
