name: Update YouTube stats

on:
  workflow_dispatch:

jobs:
  metadata-update:
    runs-on: ubuntu-latest
    steps:
    - name: Query API
      run: |
        curl 'https://youtube.googleapis.com/youtube/v3/channels?part=statistics&forUsername=Jerma985&key=${{ secrets.API_KEY }}' \
          --header 'Accept: application/json' \
          --compressed \
          -o output.json
    - name: Shuffle JSON around
      run: echo "OUTPUT_JSON=$(jq -c . < output.json)" >> $GITHUB_ENV
    - name: Output JSON for debug
      run: echo '${{ fromJson(env.OUTPUT_JSON) }}'
    - name: Output JSON for debug
      run: echo '${{ fromJson(env.OUTPUT_JSON).items[0].statistics.subscriberCount }}'


# Get list of channels
# Process all
# Output all
