name: Update YouTube stats

on:
  workflow_dispatch:

jobs:
  metadata-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout channel config file
      uses: actions/checkout@v3.5.3
      with: 
        sparse-checkout: |
          automation/channels.txt
        sparse-checkout-cone-mode: false
    - name: Updating data
      run: |
        headerPrefix="#### "
        while read line; do
          if [[ $line == $headerPrefix* ]]; then
            echo "\n\n$line\n"
            echo "| Channel | # Videos | Subscribers | Views |\n| --- | --- | --- | --- |\n"
          else
            curl "https://youtube.googleapis.com/youtube/v3/channels?part=statistics&id=$line&key=${{ secrets.API_KEY }}" \
              --header 'Accept: application/json' \
              --compressed \
              -o output.json
            cat output.json
            VIDEO_COUNT=$(jq -r '.items[0].statistics.videoCount' output.json)
            SUBSCRIBER_COUNT=$(jq -r '.items[0].statistics.subscriberCount' output.json)
            VIDEO_COUNT=$(jq -r '.items[0].statistics.viewCount' output.json)
            echo "| $line | $VIDEO_COUNT | $SUBSCRIBER_COUNT | $VIEW_COUNT |\n"
          fi
        done < ${{ github.workspace }}/automation/channels.txt
