name: Update YouTube stats

on:
  workflow_dispatch:

jobs:
  metadata-update:
    runs-on: ubuntu-latest
    steps:
    - name: Query YouTube API
      run: |
        curl 'https://youtube.googleapis.com/youtube/v3/channels?part=statistics&forUsername=Jerma985&key=${{ secrets.API_KEY }}' \
          --header 'Accept: application/json' \
          --compressed \
          -o output.json
    - name: Save JSON into env var
      run: echo "OUTPUT_JSON=$(jq -c . < output.json)" >> $GITHUB_ENV
    - name: Output JSON for debug
      run: echo '${{ env.OUTPUT_JSON }}'
    - name: Pull data out of JSON
      run: |
        echo "This channel has "
        echo "${{ fromJson(env.OUTPUT_JSON).items[0].statistics.subscriberCount }} subscribers, "
        echo "${{ fromJson(env.OUTPUT_JSON).items[0].statistics.videoCount }} videos, and "
        echo "${{ fromJson(env.OUTPUT_JSON).items[0].statistics.viewCount }} video views."
